name: minecraft_data
description: Provide easy access to minecraft data in node.js.
version: 3.5.0
homepage: https://github.com/Dart-Craft/dart-minecraft-data
issue_tracker: https://github.com/Dart-Craft/dart-minecraft-data/issues

environment:
  sdk: '>=3.0.0-204.0.dev < 4.0.0'


dev_dependencies:
  lints: ^1.0.0
