name: minecraft-data
description: Provide easy access to minecraft data in node.js.
version: 3.0.0
homepage: https://github.com/Dart-Craft/dart-minecraft-data
issue_tracker: https://github.com/Dart-Craft/dart-minecraft-data/issues

environment:
  sdk: '>=2.16.2 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
